### ISSUE TITLE
[Documentation] Link to `api_check.py` outdated in documentation

### ISSUE THREAD

**Issue by felixzinn** [scikit-hep/hepstats#167]
Hi,

In the `hypotest` part of the `getting started` section is a [link to the `api_check.py` file](https://github.com/scikit-hep/hepstats/blob/b18b218c7b3bc875bf97cbc1249fe6ad360a1f7f/docs/getting_started/hypotests.rst?plain=1#L8). However, the link seems to be outdated and the file has been moved to [`hepstats/utils/fit`](https://github.com/scikit-hep/hepstats/blob/main/src/hepstats/utils/fit/api_check.py).

**Comment by jonas-eschle** [comment]
Hi @felixzinn , thanks for noticing! Would you wanna contribute this? It should be fairly simple but a good way for a contribution. I can guide you through all the steps and what is necessary

**Comment by felixzinn** [comment]
@jonas-eschle 
sure! I can make the necessary changes.
As far as I can tell, the project uses pre-commit and pytest for which I need `hepstats[dev]`.
Anything else that I need to know?

**Comment by jonas-eschle** [comment]
Yes, exactly, that's so far all! You can just make a PR and we can take it from there. Fork it, clone it, pip install with the -e option, make a change, run pytest, run pre-commit, yep... that's all
