### ISSUE TITLE
sPlot implementation

### ISSUE THREAD

**Issue by marinang** [scikit-hep/hepstats#21]
The sPlot algorithm could be a good fit in `hepstat`. There is already a working implementation in [`hep_ml`](https://github.com/arogozhnikov/hep_ml/blob/master/notebooks/sPlot.ipynb).
I am however not sure of the freedom of implementation regarding licenses etc....

**Comment by mayou36** [comment]
The license should not be a problem, if we want to copy-paste the code, I think the apache 2 license text has to be included with the file, that's it.

**Comment by marinang** [comment]
I didn't have a particular idea. The code is pretty short if you look at
https://github.com/arogozhnikov/hep_ml/blob/master/hep_ml/splot.py.
It can be refactored for our need.

**Comment by mayou36** [comment]
yep, I agree, it looks pretty simple

**Comment by marinang** [comment]
We can have a different implementation similar to the RooStat implementation where the function computing sweights takes as argument a fit model composed of extended pdfs. The user specifies for which sub-component of the model he wants the sweights by giving the yield parameter as argument.
