### ISSUE TITLE
readthedoc docs

### ISSUE THREAD

**Issue by jonas-eschle** [scikit-hep/hepstats#44]
Currently, the docs are published on github pages. Should we also activate them again on readthedocs to have older versions as well? It fails currently since the requirements.txt is gone, but we could tell readthedocs to install the package, which should be sufficient.

Btw @marinang, I can help with that and you could add me as a maintainer in RTD, feel free to.

**Comment by eduardo-rodrigues** [comment]
Sounds a very good idea to me.

**Comment by marinang** [comment]
@jonas-eschle Hey what's you RTD username? 

![image](https://user-images.githubusercontent.com/24250309/131845906-e8c18f7e-141a-4da5-8b85-f0da096277b2.png)

**Comment by jonas-eschle** [comment]
Ah yes, there I am called Mayou36. Thanks a lot!
