### ISSUE TITLE
Make use of org scripts in scikit-hep/azure-wheel-helpers

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/hepstats#6]
Just so that we do not forget to try and use the org scripts in https://github.com/scikit-hep/azure-wheel-helpers for CI :-).

**Comment by marinang** [comment]
@eduardo-rodrigues I thought the issue was originally intended for using the scikit-hep organisation azure account, also for deployment to pypi that would be nice.
Anyway I will have a look, and adjust them for conda use.

**Comment by marinang** [comment]
Maybe @henryiii can enlighten me in this task, but it seems I would to change/remove a lot of things in https://github.com/scikit-hep/azure-wheel-helpers.

Those are my current azure pipeline files:
https://github.com/scikit-hep/scikit-stats/blob/master/azure-pipelines.yml
https://github.com/scikit-hep/scikit-stats/blob/master/.ci/azure-steps.yml

**Comment by henryiii** [comment]
Do you cave any C or C++ extensions? If not, *please build a universal wheel*! Do not build binaries. You just need that and an sdist. Please read https://iscinumpy.gitlab.io/post/azure-devops-python-wheels/

The wheel helpers are only for projects with compiled code. See Particle for an example with pure Python.

**Comment by marinang** [comment]
Nice, it is simpler. I going back to what I had and adding azure-wheel.yml

**Comment by eduardo-rodrigues** [comment]
> @eduardo-rodrigues I thought the issue was originally intended for using the scikit-hep organisation azure account, also for deployment to pypi that would be nice.
> Anyway I will have a look, and adjust them for conda use.

Hi @marinang, apologies for being effectively offline in the morning. That too - use the org account, the org scripts where possible. Seems the right thing to do to avoid duplication.

**Comment by eduardo-rodrigues** [comment]
OK, have now read the whole thread. Makes sense.

**Comment by henryiii** [comment]
The wheel generation parts look great.

I'm still planning on working on something to make sharing wheel code simpler (though very little is needed for universal wheels, so unlikely to need to worry much here). Also will look into using GitHub Actions - it's basically just rebranded Azure.

**Comment by marinang** [comment]
>  Also will look into using GitHub Actions - it's basically just rebranded Azure.

You consider using this over Azure? I just had a quick look it looks exactly like a rebranded Azure indeed.

**Comment by henryiii** [comment]
The names of things have changed, and I think they've made a few things simpler (like adding actions), the tight integration with GitHub is great. You can see all the logs in GitHub, permissions match GitHub, actions can be hosted in GitHub repositories, etc. It's still in public beta, so not moving to it full steam just yet. Also, I think they have artifacts, but unless they do the full release pipelines that Azure has, Azure might remain better for building wheels.

**Comment by henryiii** [comment]
Set a release pipeline and click a button once you are happy. Simple and gives you full control - you can even download the wheel to check them if you want before clicking. I wrote a step-by-step tutorial with pictures: https://iscinumpy.gitlab.io/post/azure-devops-releases/

**Comment by marinang** [comment]
@henryiii I soude check your blog in more details :D
