### ISSUE TITLE
Bayesian Blocking prior is astro-specific

### ISSUE THREAD

**Issue by Moelf** [scikit-hep/hepstats#80]
![image](https://user-images.githubusercontent.com/5306213/197619423-d680f35a-978d-4c0e-a4fc-46a66ffc03bb.png)

https://github.com/scikit-hep/hepstats/blob/85cdb1e9c0a2699fbe4715ff7c879f068ca7452f/src/hepstats/modeling/bayesian_blocks.py#L53-L54

**Comment by Moelf** [comment]
actually, that's a bug right? `4-` should be inside?

**Comment by Moelf** [comment]
https://arxiv.org/pdf/1304.2818.pdf should probably use this, the 2012 has wrong formula

**Comment by eduardo-rodrigues** [comment]
Thanks @Moelf for the comment! You are most welcome to submit a PR otherwise we will get to this asap.

**Comment by Moelf** [comment]
no sorry I think you guys already used the correct formula, but I think now the problem is we shouldn't default to the prior one anyway, we should use the geometric prior, because the formula in screen shot comes from fitting astrophysics data, our histograms have nothing to do with brightness sequence of stars

**Comment by jonas-eschle** [comment]
Hi @Moelf , I am myself not an expert in this, however it's not quite clear to me why a geometric prior should be used? But as @eduardo-rodrigues mentioned, you're very welcome to open a PR and we can discuss it there (I have too little time currently to dig deep enough into the topic).

**Comment by Moelf** [comment]
Because the prior and numbers you're currently using is derived from fitting a simulation of star light, nothing to do with HEP
