### ISSUE TITLE
When to support Python 3.11?

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/hepstats#99]
Hello @jonas-eschle, I guess this largely depends in practice on when zfit will be able to support 3.11. Can you comment?

I believe as soon as this is sorted I will be able to support 3.11 in scikit-hep (checking as we speak).

Many thanks.

**Comment by jonas-eschle** [comment]
Hey thanks, we're trying to get it ASAP in (waiting eagerly for that too), TF just recently upgraded to 3.11 but some deps of TF (that we also use, like TF-probability) haven't yet. Tracking the changes here: https://github.com/zfit/zfit/pull/462

**Comment by eduardo-rodrigues** [comment]
OK, thanks.

**Comment by jonas-eschle** [comment]
Hi, I am simply removing the dep in zfit, so that it becomes Python 311 compatible, hepstats therefore too. Before today, we should have the release!
